### ISSUE TITLE
playNumber LUA function 2.2

### ISSUE THREAD

**Issue by mickkn** [opentx/lua-reference-guide#28]
Will this be updated any soon? 

https://opentx.gitbooks.io/opentx-2-2-lua-reference-guide/content/general/playNumber.html

My percent value doesn't work anymore

**Comment by projectkk2glider** [comment]
Would you be willing to add this?

**Comment by projectkk2glider** [comment]
Percent (13) was not changed, are you sure you got the right 2.2 sound pack? There were some changes above 19 Degrees, which I will document.

**Comment by projectkk2glider** [comment]
Done in https://github.com/opentx/opentx/commit/dcbfa92b039803bd7d80df57ebfdcb16f0aa2160
