### ISSUE TITLE
Script Writing off screen/ Tx scratch 

### ISSUE THREAD

**Issue by RCdiy** [opentx/lua-reference-guide#35]
Current documentation implies that scripts won't crash radio. Suggest adding documentation that programmers must ensure drawing within lcd limits. See discussion https://www.rcgroups.com/forums/showthread.php?2180477-LUA-scripting-Technical-discussion/page149#post37781551

**Comment by projectkk2glider** [comment]
Scripts must not crash the radio, if they do, bug must be found and fixed.

**Comment by RCdiy** [comment]
Thread to read
https://www.rcgroups.com/forums/showthread.php?p=37772841&postcount=2207

**Comment by RCdiy** [comment]
Script but found and fixed or OpenTX bug found an fixed?

**Comment by projectkk2glider** [comment]
OpenTX bug found, but not yet fixed (it will be when issue #5055 closes).
