### ISSUE TITLE
LCD dimensions appendix

### ISSUE THREAD

**Issue by RCdiy** [opentx/lua-reference-guide#37]
I plan on doing up a list/table for LCD dimensions LCD_W/LCD_H for the radios... if an admin creates a place holder page for me in the appendix I'll add in the contents.. please @rcdiy me when added...

**Comment by RCdiy** [comment]
| Radio | LCD_W | LCD_H |
| --- | --- | --- |
| ARUni | 128 | 64 |
| MEGA2560 | ? | ? |
| X7 | 128 | 64 |
| X9D | 212 | 64 |
| X9D+ | 212 | 64 |
| X9E | 212 | 64 |
| X12S | 480 | 272 |
| 9X | 128 | 64 |
| 9XR | 128 | 64 |

**Comment by projectkk2glider** [comment]
Lua is only available on radios with ARM based processors, which are currently: X7, X10, X12, X9D(+) and X9E. Upcoming X10 has same display as X12.

You might also want to include number of colors:
 * X7  black and white
 * X9D(+) and X9E grayscale
 * X10 and X12 color

**Comment by projectkk2glider** [comment]
@RCdiy I would just add the contents to the existing page https://github.com/opentx/lua-reference-guide/blob/opentx_2.2/lcd/lcd_functions-overview.md

Remember to work on the `opentx_2.2` branch **and not** on the `master` branch (which is for OpenTX 2.1).

**Comment by RCdiy** [comment]
Updated table above... it it okay? @projectkk2glider

**Comment by MikeBland** [comment]
The SKY, AR9X, ARUNI and 9XR-PRO radios have ATMEL ARM processors, and, I understand, LUA is not available on them, so the statement "Lua is only available on radios with ARM based processors" is not correct.
As a note, I did implement LUA in esky9x and run it on these.
I have upgraded an AR9X board to have an ATSAM4S8CA (128K RAM), so this would support LUA OK. I understand the next batch of ARUNI boards are likely to have this processor.

Mike.

**Comment by RCdiy** [comment]
Before I submit a pull request is my table okay?
Where I say colour is the a bit depth I need to provide?

**Comment by kilrah** [comment]
You can say it's RGB565.

**Comment by RCdiy** [comment]
Updated table

**Comment by bsongis** [comment]
@MikeBland Lua could be easily added, but how much RAM is available once the interpreter is properly initialized?

**Comment by projectkk2glider** [comment]
@RCdiy why did you close this? The new content was not added to the manual yet. The table is perfect.

@MikeBland we could modify my sentence with: "Lua is only available on radios with ARM based processors **that have enough hardware resources**"

**Comment by RCdiy** [comment]
That statement is not being added in the lcd section. Maybe start a new issue?
As someone who knows less than the developers here I suggest that if you are putting in that statement make it easier for me by saying something like:
Lua scripts can be added to the following radios:
- provide a list

**Comment by RCdiy** [comment]
I did add it. Maybe forgot the pull request.

**Comment by RCdiy** [comment]
Reopening pending merge...

**Comment by MikeBland** [comment]
@bsongis Just checked on an AR9X board with a SAM4S (128K RAM). With the radio running, but no LUA script run, I have 86016 bytes free. After running a small script that displays a few numbers and lines, I have 77824 bytes free.

**Comment by bsongis** [comment]
We should then say "Lua is only available on radios with ARM based processors that have at least 128K RAM". Is there one of the radio you originally mentionned (SKY, AR9X, ARUNI and 9XR-PRO) with 128K that I can buy somewhere?

**Comment by MikeBland** [comment]
No (at least not yet). I believe the next batch of ARUNI boards will have SAM4S processors on them.
I swapped the processor on an AR9X board for testing.

**Comment by kilrah** [comment]
At this point in our context it's "Lua is only supported on FrSky radios", easy.
