### ISSUE TITLE
List of valid sources disapeared form server

### ISSUE THREAD

**Issue by JimB40** [opentx/lua-reference-guide#50]
Thera are no more txt files of valid sources for getFieldInfo(name) function
![Screen Shot 2020-04-27 at 22 17 49](https://user-images.githubusercontent.com/46420768/80417722-7ecd8b00-88d6-11ea-9ccd-020f27bfe199.png)

**Comment by bsongis** [comment]
Fixed by @3djc

**Comment by JimB40** [comment]
Still no files of valid sources for 2.2 linked here
https://opentx.gitbooks.io/opentx-2-2-lua-reference-guide/content/general/getFieldInfo.html

![Screen Shot 2020-05-04 at 14 46 54](https://user-images.githubusercontent.com/46420768/80967240-4e29ac00-8e16-11ea-8e0e-d1f8638829a0.png)
![Screen Shot 2020-05-04 at 14 47 05](https://user-images.githubusercontent.com/46420768/80967244-4ff36f80-8e16-11ea-8a41-fd05da7cc930.png)
![Screen Shot 2020-05-04 at 14 47 22](https://user-images.githubusercontent.com/46420768/80967246-508c0600-8e16-11ea-93e8-1439a1a4f470.png)

**Comment by udyux** [comment]
This issue was not resolved.
