### ISSUE TITLE
A process to generate function documentation from the sources

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/lua-reference-guide#7]
Original idea came from Bertrand. 

We should try to develop a system that allows us to document OpenTX Lua API functions in the source code files (like Doxygen style documentation) and then have a python script that will auto-generate files and their contents in markdown format that will be directly useable in the gitbook.

Other parts of the Lua manual will still be developed in the current way. So the automatic docs generation would only document the https://github.com/opentx/lua-reference-guide/blob/master/part_iii_-_opentx_lua_api_reference.md

So the process would be:
* write documentation for each Lua exported function in the source code, rigth there where the actual function implementing it is defined. This way we have a better chance to keep the actual function functionality and it's documentation in sync.
* in-source documentation format is still yet to be decided, possible options are:
  * directly use the markdown
  * use (simplified) Doxygen format
* when we decide to update the docs (gitbook) we run the custom python script that will:
  * parse lua_api.cpp file from OpenTX repository
  * look for special comment sections that contain documentation
  * parse and format each documentation section and generate a markdown file for each function.
  * script could also generate a subsection of index for generated functions (that goes into SUMMARY.md)

Comments welcome

**Comment by projectkk2glider** [comment]
I have started on custom python script. Currently it parses documentation in the form of:
```c
/*luadoc
@function model.setGlobalVariable(index, phase, value)

The @func() function is used to set current global variable
value. See also model.luaModelGetGlobalVariable()


@param index  zero based global variable index, use 0 for GV1, 8 for GV9
@param phase  long comment,
              on multiple lines
@param value  new value for global variable. Permitted range is
              from -1024 to 1024. 

@retval none

@notice Global variable can only store integer values, any floating point value
        is converted (todo check how) into integer value.
*/
``` 

And produces markdown:
```
## model.setGlobalVariable(index, phase, value)

#### Parameters

* `index`  zero based global variable index, use 0 for GV1, 8 for GV9
* `phase`  long comment, on multiple lines
* `value`  new value for global variable. Permitted range is from -1024 to 1024.

#### Return

* `none` 

---
The @func() function is used to set current global variable
value. See also model.luaModelGetGlobalVariable()


##### Notice

* Global variable can only store integer values, any floating point value is converted (todo check how) into integer value.
```
Which renders (on gitboo it is a little diferent:

## model.setGlobalVariable(index, phase, value)

#### Parameters

* `index`  zero based global variable index, use 0 for GV1, 8 for GV9
* `phase`  long comment, on multiple lines
* `value`  new value for global variable. Permitted range is from -1024 to 1024.

#### Return

* `none` 

---
The @func() function is used to set current global variable
value. See also model.luaModelGetGlobalVariable()


##### Notice

* Global variable can only store integer values, any floating point value is converted (todo check how) into integer value.

**Comment by bsongis** [comment]
Good job!

**Comment by dsbeach** [comment]
I like the idea and the consistent formatting.  However, I'm wondering if there might be a way to enhance this approach to include an example script and sample output.

Look at https://opentx.gitbooks.io/opentx-lua-reference-guide/content/gettime.html

Could the python script detect the existence of  "gettime.lua" and/or "gettime.png" (ideally in the book's git repository) and generate the appropriate markdown?

I think examples have a lot of value, and would appreciate their inclusion.

**Comment by projectkk2glider** [comment]
>Could the python script detect the existence of "gettime.lua" and/or "gettime.png" (ideally in the book's git repository) and generate the appropriate markdown?

Sure, nice idea, the script could look for a predefined name pattern for examples and include them on the same page as the function documentation itself.

**Comment by projectkk2glider** [comment]
Some progress:
* script and result: https://github.com/opentx/lua-reference-guide/compare/projectkk2glider/issue_7_docs_from_sources
* start of lua docs: https://github.com/opentx/opentx/commit/f4e905dda723f7d4189f1495a2c9e16e5d790b91

Usage:
* edit lua_api.cpp (in OpenTX project) to add/edit documentation.
* run the generator script from the root directory of this repository:
```
./tools/generate-api-docs.py  ../opentx/radio/src/lua_api.cpp
```
* paste the output to SUMMARY.md if needed (to add links to new pages for example)
* test the book locally (one has to install gitbok localy, a simple process on Linux):
```
$ gitbook serve
```
* push changes to the repository.

**Comment by dsbeach** [comment]
Cool - I'll have a look at it tomorrow!

**Comment by dsbeach** [comment]
Looks good.  I'm holding off on further documentation updates until this process is in place.

The approach you are taking relative to examples is not what I was expecting. I like the idea of allowing for multiple examples, but was expecting the example files to be .lua files whose content was included inline in the documentation wrapped in appropriate code markdown.

Thus, if file setGlobalVariable-example01.lua exists, it's contents would be included in the markdown generated for setGlobalVariable().

<cite>
   ...
   #####Example 01:
    \`\`\`lua 
    the contents of setGlobalVariable-example01.lua go here
    \`\`\`
    ...
<cite>

I was thinking it might be easier to maintain the examples that way.

**Comment by projectkk2glider** [comment]
I am not sure you know how the examples work, so I will explain it here and perhaps you will be satisfied. If not, we can make changes.

So, lets take one function `model.getValue()`, its auto generated documentation (md format) will end up in a directory `model` in a file `getValue.md`. 

The script will generate the contents from the documentation in lua_api.cpp **and** then append verbatim contents of all found files that match the following pattern: `model/getValue-exampleNN.md` where NN is a nuber from 00 to 99. They will also be numerically ordered so 00 will be included before 01, etc.

So, yes the script does not format the content of examples, it just includes them as they are, that brings following benefits:
* custom layout (which might also be a negative thing)
* ability to add explanation texts to the example, include links to images, etc..

I think the current system is very flexible. If we take your proposal, how would you add explanation texts to the example Lua code and how would you add images?

There is one example of this scheme in a file https://github.com/opentx/lua-reference-guide/blob/projectkk2glider/issue_7_docs_from_sources/model/setGlobalVariable-example01.md which in included in https://github.com/opentx/lua-reference-guide/blob/projectkk2glider/issue_7_docs_from_sources/model/setGlobalVariable.md

**Comment by dsbeach** [comment]
I agree it is flexible, however with examples as .md files there is a greater opportunity to introduce syntax errors resulting in examples that may not work when cut and pasted.

I would advocate including explanations in examples as lua comments. When a sample is wrapped by Lua syntax highlighting the result is very readable.

Your setGlobalVariable example is not wrapped by syntax highlighting which I think is important. I realize that it could be done within an example.md file, but I'd be much more likely to develop examples if it was just a matter of checking in a tested .lua file following appropriate naming conventions.

Similarly, I suggest the python script detect image files showing example output following some naming convention, and generating the image markdown when they are found.

I'm sure the way you are processing things now will work, and has more flexibility. It's just that I would prefer keeping examples as .lua files.  I think it is easier and less prone to possible error or style deviations.

**Comment by projectkk2glider** [comment]
OK, I agree with you, but I will leave existing functionality in (it won't interfere with anything if not used) and will add your proposals like so:
* any `<module_name>/<functon_name>-exampleNN.lua` file will be added as a Lua code
* any  `<module_name>/<functon_name>-exampleNN.png` will be added as an image link

The ordering will be global so 05.lua will be before the 06.png. Would that be OK with you?

**Comment by dsbeach** [comment]
Sounds good.

I'm assuming you intended to say 05.lua will precede 05.png. But what if there is also an 05.md file?  Should it come first? I think the answer is yes - but since the filenames will not be exposed in the documentation it may not matter and we can just name the files as needed to sequence the output.

I'd also suggest they be processed independently. It sould be OK to have Lua examples without images and/or images without Lua examples.

**Comment by projectkk2glider** [comment]
The order of the examples (md, lua and png) will solely depend on their number. If they have the same number, then the order is not defined.

In your example if you want lua to precede png then name them 05.lua and 06.png. You can also skip numbers if you want, so you could name them 05.lua and 56.png. If there is no other file with a number between 06 and 55 ,then those two files will be one after the other.
